version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - .default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi

  fastapi:
    image: demigorrgon/coinapi_endpoints:latest
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    ports:
      - 8000:8000
